version = 0.1
[default.deploy.parameters]
stack_name = "sam-app-ps"
resolve_s3 = true
s3_prefix = "sam-app-ps"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "VpcStackName=\"\" CodeSigningConfigArn=\"none\" LambdaDeploymentPreference=\"Canary10Percent5Minutes\" PermissionsBoundary=\"none\" Environment=\"\" NotificationTopicArn=\"none\""
image_repositories = []
