AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: >
  devplatform-deploy canary-circuit-breaker template version: v0.0.0
  Canary deployment circuit breaker template managed by dev-platform.

Parameters:
  Environment:
    Description: "The name of the environment to deploy to"
    Type: "String"
    AllowedValues:
      - build
      - staging
      - production
      - integration
      - demo
      - local
      - dev

  GovUKMobileCognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Join
        - "-"
        - - !Ref AWS::StackName
          - "user-pool"
          - Fn::Select:
              - 4
              - Fn::Split:
                  - "-"
                  - Fn::Select:
                      - 2
                      - Fn::Split:
                          - "/"
                          - Ref: AWS::StackId
      DeletionProtection: ACTIVE
      UsernameAttributes:
        - email
      Schema:
        - AttributeDataType: String
          Name: email
          Required: true
      UserPoolTags:
        Product: GOV.UK
        Environment: !Ref Environment
        System: Authentication
