AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: >
  devplatform-deploy canary-circuit-breaker template version: v0.0.0
  Canary deployment circuit breaker template managed by dev-platform.

Parameters:
  Environment:
    Description: "The environment we're deploying into."
    Type: "String"
    Default: dev
    AllowedValues:
      - "dev"
      - "build"
      - "staging"
      - "integration"
      - "production"

Resources:
  CircuitBreakerTriggerEventRule:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        source:
          - aws.codedeploy
        detail-type:
          - CodeDeploy Deployment State-change Notification
        detail:
          state:
            - STOP
            - FAILURE

  GovUKMobileCognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Join
        - "-"
        - - !Ref AWS::StackName
          - "user-pool"
          - Fn::Select:
              - 4
              - Fn::Split:
                  - "-"
                  - Fn::Select:
                      - 2
                      - Fn::Split:
                          - "/"
                          - Ref: AWS::StackId
      DeletionProtection: ACTIVE
      Policies:
        PasswordPolicy:
          MinimumLength: 0
      UsernameAttributes:
        - email
      Schema:
        - AttributeDataType: String
          Name: email
          Required: true
      UserPoolTags:
        Product: GOV.UK
        Environment: build
        System: Authentication
