AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: >
  devplatform-deploy canary-circuit-breaker template version: v0.0.0
  Canary deployment circuit breaker template managed by dev-platform.

Resources:
  CircuitBreakerTriggerEventRule:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        source:
          - aws.codedeploy
        detail-type:
          - CodeDeploy Deployment State-change Notification
        detail:
          state:
            - STOP
            - FAILURE