repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    hooks:
      - id: check-merge-conflict
    rev: v5.0.0
  - repo: git@github.com:Yelp/detect-secrets
    hooks:
      - args:
          - --baseline
          - .secrets.baseline
        id: detect-secrets
    rev: v1.5.0
  - repo: local
    hooks:
      - id: pre-flight-checks
        name: pre-flight-checks
        language: script
        entry: pre-commit.sh
        pass_filenames: false
        stages: [pre-commit]
      - id: format
        name: format
        entry: npm run format:check
        pass_filenames: false
        stages: [pre-commit]
        language: system
      - id: linting
        name: linting
        language: system
        entry: nx affected -t lint
        pass_filenames: false
        stages: [pre-commit]
      - id: unit-tests
        name: unit-tests
        language: system
        entry: nx affected -t test:unit
        pass_filenames: false
        stages: [pre-commit]
      - id: checkov
        name: checkov-sam-template-scan
        language: system
        entry: nx affected -t checkov
        pass_filenames: false
        stages: [pre-commit]

      - id: acceptance tests
        name: acceptance tests
        language: system
        entry: nx affected -t auth:test:acc
        pass_filenames: false
        stages: [pre-push]

      - id: integration tests
        name: integration tests
        language: system
        entry: nx affected -t auth:test:int
        pass_filenames: false
        stages: [pre-push]
