AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: >
  devplatform-deploy canary-circuit-breaker template version: v0.0.0
  Canary deployment circuit breaker template managed by dev-platform.

Parameters:
  Environment:
    Description: "The name of the environment to deploy to"
    Type: "String"
    AllowedValues:
      - build
      - staging
      - production
      - integration
      - demo
      - local
      - dev

  CodeSigningConfigArn:
    Type: String
    Description: >
      The ARN of the Code Signing Config to use, provided by the deployment pipeline
    Default: "none"

  PermissionsBoundary:
    Type: String
    Description: >
      The ARN of the permissions boundary to apply to any role created by the template
    Default: "none"

Conditions:
  UseCodeSigning:
    Fn::Not:
      - Fn::Equals:
          - !Ref CodeSigningConfigArn
          - "none"

  UsePermissionsBoundary:
    Fn::Not:
      - Fn::Equals:
          - !Ref PermissionsBoundary
          - "none"

Globals:
  Function:
    CodeSigningConfigArn: !If
      - UseCodeSigning
      - !Ref CodeSigningConfigArn
      - !Ref AWS::NoValue
    PermissionsBoundary: !If
      - UsePermissionsBoundary
      - !Ref PermissionsBoundary
      - !Ref AWS::NoValue
    MemorySize: 128
    Timeout: 60
    Runtime: nodejs22.x

Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Join
        - "-"
        - - !Ref AWS::StackName
          - "user-pool"
          - Fn::Select:
              - 4
              - Fn::Split:
                  - "-"
                  - Fn::Select:
                      - 2
                      - Fn::Split:
                          - "/"
                          - Ref: AWS::StackId
      DeletionProtection: ACTIVE
      UsernameAttributes:
        - email
      Schema:
        - AttributeDataType: String
          Name: email
          Required: true
      UserPoolTags:
        Product: GOV.UK
        Environment: !Ref Environment
        System: Authentication
      LambdaConfig:
        PreAuthentication: !GetAtt PreAuthenticationFn.Arn
        PostAuthentication: !GetAtt PostAuthenticationFunction.Arn

  PreAuthCognitoLambdaInvokePermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !GetAtt PreAuthenticationFn.Arn
      Principal: "cognito-idp.amazonaws.com"
      SourceArn: !Sub arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${CognitoUserPool}

  WebApplicationFirewall:

  GovUKMobileCognitoUserClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref GovUKMobileCognitoUserPool
      ClientName: !Join
        - "-"
        - - !Ref AWS::StackName
          - "user-pool-client"
          - Fn::Select:
              - 4
              - Fn::Split:
                  - "-"
                  - Fn::Select:
                      - 2
                      - Fn::Split:
                          - "/"
                          - Ref: AWS::StackId
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - email
      SupportedIdentityProviders:
        - COGNITO
      CallbackURLs:
        - !Join
          - ""
          - - "https://"
            - !Ref AWS::StackName
            - "."
            - !Ref Environment
            - ".gov.uk/auth/callback" # Replace with "https://your-production-domain.gov.uk/auth/callback" before deployment
      LogoutURLs:
          - !Join
            - ""
            - - "https://"
              - !Ref AWS::StackName
              - "."
              - !Ref Environment
              - ".gov.uk/auth/logout" # Replace with actual logout URL TBD
      DefaultRedirectURI:
          - !Join
            - ""
            - - "https://"
              - !Ref AWS::StackName
              - "."
              - !Ref Environment
              - ".gov.uk/auth/callback" # Replace with actual callback URL TBD
      AccessTokenValidity: 3600 # 1 hour
      IdTokenValidity: 3600 # 1 hour
      RefreshTokenValidity: 31536000 # 1 year in seconds (365 days * 24 hours * 3600 seconds)

    GovUKMobileWebApplicationFirewall:
    Type: AWS::WAFv2::WebACL
    Properties:
      DefaultAction:
        Allow: {}
      Scope: REGIONAL
      VisibilityConfig:
        CloudWatchMetricsEnabled: true
        MetricName: !Join
          - "-"
          - - !Ref AWS::StackName
            - "waf-acl-rules"
            - Fn::Select:
                - 4
                - Fn::Split:
                    - "-"
                    - Fn::Select:
                        - 2
                        - Fn::Split:
                            - "/"
                            - Ref: AWS::StackId
        SampledRequestsEnabled: true
      Tags:
        - Key: Product
          Value: GOV.UK
        - Key: Environment
          Value: !Ref Environment
        - Key: System
          Value: Authentication

  CognitoWAFAssociation:
    Type: AWS::WAFv2::WebACLAssociation
    Properties:
      ResourceArn: !GetAtt CognitoUserPool.Arn
      WebACLArn: !GetAtt WebApplicationFirewall.Arn

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Join
        - "-"
        - - !Ref AWS::StackName
          - "api-gateway"
          - Fn::Select:
              - 4
              - Fn::Split:
                  - "-"
                  - Fn::Select:
                      - 2
                      - Fn::Split:
                          - "/"
                          - Ref: AWS::StackId
      StageName: !Ref Environment
      Tags:
        Product: GOV.UK
        Environment: !Ref Environment
        System: Authentication

  PostAuthenticationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: post-authentication-function/
      Handler: app.lambdaHandler
      Tags:
        Product: GOV.UK
        Environment: !Ref Environment
        System: Authentication
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        SourceMap: false
        EntryPoints:
          - app.ts

  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGateway
            Path: /test
            Method: GET
      Tags:
        Product: GOV.UK
        Environment: !Ref Environment
        System: Authentication
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        SourceMap: false
        EntryPoints:
          - app.ts

  PreAuthenticationFn:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handler
      Runtime: nodejs22.x
      CodeUri: ./pre-authentication
      MemorySize: 128
      Timeout: 30
      Tags:
        Product: GOV.UK
        Environment: !Ref Environment
        System: Authentication
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
        - app.ts

Outputs:
  ApiGateway:
    Description: API Gateway endpoint URL Hello World function
    Value: !Sub https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/test/
