AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: >
  devplatform-deploy canary-circuit-breaker template version: v0.0.0
  Canary deployment circuit breaker template managed by dev-platform.

Parameters:
  Environment:
    Description: "The name of the environment to deploy to"
    Type: "String"
    AllowedValues:
      - build
      - staging
      - production
      - integration
      - demo
      - local
      - dev

  CodeSigningConfigArn:
    Type: String
    Description: >
      The ARN of the Code Signing Config to use, provided by the deployment pipeline
    Default: "none"

  PermissionsBoundary:
    Type: String
    Description: >
      The ARN of the permissions boundary to apply to any role created by the template
    Default: "none"

Mappings:
  OneLogin:
    Environment:
      build: "staging"
      dev: "staging"
      staging: "staging"
      integration: "integration"
      production: "production"

Conditions:
  UseCodeSigning:
    Fn::Not:
      - Fn::Equals:
          - !Ref CodeSigningConfigArn
          - "none"

  UsePermissionsBoundary:
    Fn::Not:
      - Fn::Equals:
          - !Ref PermissionsBoundary
          - "none"

Globals:
  Function:
    CodeSigningConfigArn: !If
      - UseCodeSigning
      - !Ref CodeSigningConfigArn
      - !Ref AWS::NoValue
    PermissionsBoundary: !If
      - UsePermissionsBoundary
      - !Ref PermissionsBoundary
      - !Ref AWS::NoValue
    MemorySize: 128
    Timeout: 60
    Runtime: nodejs22.x

Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Join
        - "-"
        - - !Ref AWS::StackName
          - "user-pool"
          - Fn::Select:
              - 4
              - Fn::Split:
                  - "-"
                  - Fn::Select:
                      - 2
                      - Fn::Split:
                          - "/"
                          - Ref: AWS::StackId
      DeletionProtection: ACTIVE
      UsernameAttributes:
        - email
      Schema:
        - AttributeDataType: String
          Name: email
          Required: true
      UserPoolTags:
        Product: GOV.UK
        Environment: !Ref Environment
        System: Authentication
      LambdaConfig:
        PostAuthentication: !GetAtt PostAuthenticationFunction.Arn

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref CognitoUserPool
      ClientName: !Join
        - "-"
        - - !Ref AWS::StackName
          - "user-pool-client"
          - Fn::Select:
              - 4
              - Fn::Split:
                  - "-"
                  - Fn::Select:
                      - 2
                      - Fn::Split:
                          - "/"
                          - Ref: AWS::StackId
      SupportedIdentityProviders:
        - COGNITO
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - email
        - openid
      GenerateSecret: false  # pragma: allowlist secret
      CallbackURLs:
        - !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/test/"
      TokenValidityUnits:
        AccessToken: seconds
        IdToken: seconds
        RefreshToken: seconds
      AccessTokenValidity: 3600 # 1 hour in seconds
      IdTokenValidity: 3600 # 1 hour in seconds
      RefreshTokenValidity: 31536000 # 1 year in seconds (365 days * 24 hours * 3600 seconds)

  WebApplicationFirewall:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: !Join
        - "-"
        - - !Ref AWS::StackName
          - "waf"
          - Fn::Select:
              - 4
              - Fn::Split:
                  - "-"
                  - Fn::Select:
                      - 2
                      - Fn::Split:
                          - "/"
                          - Ref: AWS::StackId
      DefaultAction:
        Allow: {}
      Scope: REGIONAL
      VisibilityConfig:
        CloudWatchMetricsEnabled: true
        MetricName: !Join
          - "-"
          - - !Ref AWS::StackName
            - "waf-acl-rules"
            - Fn::Select:
                - 4
                - Fn::Split:
                    - "-"
                    - Fn::Select:
                        - 2
                        - Fn::Split:
                            - "/"
                            - Ref: AWS::StackId
        SampledRequestsEnabled: true
      Rules:
        - Name: RateLimitRule
          Action:
            Block:
              CustomResponse:
                ResponseCode: 429
          Priority: 1
          Statement:
            RateBasedStatement:
              AggregateKeyType: IP
              Limit: 300
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: !Join
              - "-"
              - - !Ref AWS::StackName
                - "rate-limit-rule"
                - Fn::Select:
                    - 4
                    - Fn::Split:
                        - "-"
                        - Fn::Select:
                            - 2
                            - Fn::Split:
                                - "/"
                                - Ref: AWS::StackId
            SampledRequestsEnabled: true
      Tags:
        - Key: Product
          Value: GOV.UK
        - Key: Environment
          Value: !Ref Environment
        - Key: System
          Value: Authentication

  CognitoWAFAssociation:
    Type: AWS::WAFv2::WebACLAssociation
    Properties:
      ResourceArn: !GetAtt CognitoUserPool.Arn
      WebACLArn: !GetAtt WebApplicationFirewall.Arn

  WAFLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      DataProtectionPolicy:
        Name: CloudWatchLogs-PersonalInformation-Protection
        Description: Protect basic types of sensitive data
        Version: "2021-06-01"
        Statement:
          - Sid: audit-policy
            DataIdentifier:
              - arn:aws:dataprotection::aws:data-identifier/EmailAddress
            Operation:
              Audit:
                FindingsDestination: {}
          - Sid: redact-policy
            DataIdentifier:
              - arn:aws:dataprotection::aws:data-identifier/EmailAddress
            Operation:
              Deidentify:
                MaskConfig: {}
      LogGroupClass: STANDARD
      LogGroupName: !Sub "aws-waf-logs-${AWS::StackName}"
      KmsKeyId: !GetAtt WAFLogGroupKMSKey.Arn
      RetentionInDays: 30
      Tags:
        - Key: Product
          Value: GOV.UK
        - Key: Environment
          Value: !Ref Environment
        - Key: System
          Value: Authentication

  WAFLoggingConfiguration:
    Type: AWS::WAFv2::LoggingConfiguration
    Properties:
      LogDestinationConfigs:
        - !GetAtt WAFLogGroup.Arn
      ResourceArn: !GetAtt WebApplicationFirewall.Arn

  WAFLogGroupKMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: Encryption for WAF logs
      EnableKeyRotation: true
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action:
              - "kms:*"
            Resource:
              - "*"
          - Effect: Allow
            Principal:
              Service: !Sub "logs.${AWS::Region}.amazonaws.com"
            Action:
              - "kms:Encrypt*"
              - "kms:Decrypt*"
              - "kms:ReEncrypt*"
              - "kms:GenerateDataKey*"
              - "kms:Describe*"
            Resource:
              - "*"
            Condition:
              ArnLike:
                "kms:EncryptionContext:aws:logs:arn": !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*"
      Tags:
        - Key: Product
          Value: GOV.UK
        - Key: Environment
          Value: !Ref Environment
        - Key: System
          Value: Authentication

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Join
        - "-"
        - - !Ref AWS::StackName
          - "api-gateway"
          - Fn::Select:
              - 4
              - Fn::Split:
                  - "-"
                  - Fn::Select:
                      - 2
                      - Fn::Split:
                          - "/"
                          - Ref: AWS::StackId
      StageName: !Ref Environment
      Tags:
        Product: GOV.UK
        Environment: !Ref Environment
        System: Authentication

  PostAuthenticationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: post-authentication-function/
      Handler: app.lambdaHandler
      Tags:
        Product: GOV.UK
        Environment: !Ref Environment
        System: Authentication
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        SourceMap: false
        EntryPoints:
          - app.ts

  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGateway
            Path: /test
            Method: GET
      Tags:
        Product: GOV.UK
        Environment: !Ref Environment
        System: Authentication
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        SourceMap: false
        EntryPoints:
          - app.ts

  AuthProxyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: proxy/
      Handler: app.lambdaHandler
      Environment:
        Variables:
          COGNITO_URL: !Sub "https://${CognitoUserPool}.auth.${AWS::Region}.amazoncognito.com"
      Tags:
        Product: GOV.UK
        Environment: !Ref Environment
        System: Authentication
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - app.ts

  UserPoolIdentityProvider:
    Type: "AWS::Cognito::UserPoolIdentityProvider"
    Properties:
      UserPoolId: !Ref CognitoUserPool
      ProviderName: "onelogin"
      ProviderType: "OIDC"
      ProviderDetails:
        attributes_request_method: "GET"
        attributes_url: !Join
          - ""
          - - "https://oidc."
            - !FindInMap [OneLogin, Environment, !Ref Environment]
            - ".account.gov.uk/userinfo"
        attributes_url_add_attributes: false
        authorize_scopes: "openid email"
        authorize_url: !Join
          - ""
          - - "https://oidc."
            - !FindInMap [OneLogin, Environment, !Ref Environment]
            - ".account.gov.uk/authorize"
        client_id: "{{resolve:ssm:/onelogin/client_id}}"
        client_secret: "{{resolve:secretsmanager:/onelogin/client_secret:SecretString}}" # pragma: allowlist secret
        jwks_uri: !Join
          - ""
          - - "https://oidc."
            - !FindInMap [OneLogin, Environment, !Ref Environment]
            - ".account.gov.uk/.well-known/jwks.json"
        oidc_issuer: !Join
          - ""
          - - "https://oidc."
            - !FindInMap [OneLogin, Environment, !Ref Environment]
            - ".account.gov.uk"
        token_url: !Join
          - ""
          - - "https://oidc."
            - !FindInMap [OneLogin, Environment, !Ref Environment]
            - ".account.gov.uk/token"
      IdpIdentifiers:
        - onelogin
      AttributeMapping:
        email: email
        username: sub

  AuthProxyApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: AuthProxyApi
      ProtocolType: HTTP

  AuthProxyIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref AuthProxyApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt AuthProxyFunction.Arn
      IntegrationMethod: POST
      PayloadFormatVersion: "2.0"

  AuthProxyRouteCatchAll:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref AuthProxyApi
      RouteKey: "ANY /{proxy+}"
      Target: !Join ["/", ["integrations", !Ref AuthProxyIntegration]]

  AuthProxyRouteAuthorize:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref AuthProxyApi
      RouteKey: "GET /oauth2/authorize"
      Target: !Join ["/", ["integrations", !Ref AuthProxyIntegration]]

  AuthProxyRouteToken:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref AuthProxyApi
      RouteKey: "POST /oauth2/token"
      Target: !Join ["/", ["integrations", !Ref AuthProxyIntegration]]

  AuthProxyStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref AuthProxyApi
      StageName: !Ref Environment
      AutoDeploy: true

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref AuthProxyFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${AuthProxyApi}/*/*/*

Outputs:
  ApiGateway:
    Description: API Gateway endpoint URL Hello World function
    Value: !Sub https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/test/

  AuthProxy:
    Description: Auth Proxy Gateway endpoint URL
    Value: !Sub https://${AuthProxyApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/

  UserPoolId:
    Description: ID of the Cognito User Pool
    Value: !Ref CognitoUserPool

  UserPoolProviderUrl:
    Description: The URL of the Cognito User Pool
    Value: !Sub https://cognito-idp.${AWS::Region}.amazonaws.com/${CognitoUserPool}
