AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: >
  GOVUK Mobile Attestation Module

Resources:
  PreAuthenticationFn:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handler
      Runtime: nodejs22.x 
      CodeUri: ./pre-authentication
      MemorySize: 128
      Timeout: 30
    Metadata: 
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - app.ts


Outputs:
  PreAuthenticationArn:
    Description: "ARN of the Pre Auth Lambda"
    Value: !GetAtt PreAuthenticationFn.Arn