AWSTemplateFormatVersion: "2010-09-09"

Description: |
  SAM template for attestation alarms

Parameters:
  ApiId:
    Description: ID of the attestation api
    Type: String

  ApiLogGroupName:
    Description: Name of the attestation proxy log group
    Type: String

  AlarmTopic:
    Description: The name of Attestation Alerts SNS topic
    Type: String

  Environment:
    Description: The name of the environment to deploy to
    Type: String
    AllowedValues:
      - build
      - staging
      - production
      - integration
      - demo
      - local
      - dev

  LambaName:
    Description: Name of the attestation proxy
    Type: String

  FunctionLogGroupName:
    Description: Name of the attestation proxy log group
    Type: String

  EnableAlarm:
    Type: String
    Default: "False"
    AllowedValues:
      - "True"
      - "False"
    Description: Set to "True" to disable alarms, "False" to enable alarms

Transform: AWS::Serverless-2016-10-31

Resources:
  Attestation200ResponseCountMetricFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      FilterPattern: '{ ($.resourcePath = "/oauth2/token") && ($.status = "200") }'
      LogGroupName: !Ref ApiLogGroupName
      MetricTransformations:
        - MetricName: Attestation200ResponseCount
          MetricNamespace: !Sub ${AWS::StackName}/Responses
          MetricValue: "1"

  AttestationLambdaErrorRateAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmDescription: "Alarm for high number of attestation errors. \nSee resolution steps in runbook: \nhttps://gov-uk.atlassian.net/wiki/spaces/GOVUK/pages/4517658627/Runbook+High+number+of+attestation+failures\n"
      AlarmName: !Sub ${AWS::StackName}-attestation-lambda-error-rate
      ComparisonOperator: GreaterThanOrEqualToThreshold
      DatapointsToAlarm: 1
      EvaluationPeriods: 1
      Metrics:
        - Id: lambdaInvocations
          Label: Sum of invocations
          MetricStat:
            Metric:
              Dimensions:
                - Name: Resource
                  Value: !Ref LambaName
                - Name: FunctionName
                  Value: !Ref LambaName
              MetricName: Invocations
              Namespace: AWS/Lambda
            Period: 60
            Stat: Sum
          ReturnData: false
        - Id: lambdaErrors
          Label: Sum of attestation errors
          MetricStat:
            Metric:
              Dimensions:
                - Name: Resource
                  Value: !Ref LambaName
                - Name: FunctionName
                  Value: !Ref LambaName
              MetricName: Errors
              Namespace: AWS/Lambda
            Period: 60
            Stat: Sum
          ReturnData: false
        - Expression: (lambdaErrors / lambdaInvocations)*100
          Id: lambdaErrorPercentage
          Label: Percentage of invocations that result in a function error
          ReturnData: false
        - Expression: IF(lambdaInvocations>=10, lambdaErrorPercentage)
          Id: lambdaErrorPercentageHighTraffic
          Label: Percentage of invocations that result in a function error with at least 10 invocations a minute
          ReturnData: true
      AlarmActions:
        - !Ref AlarmTopic
      OKActions:
        - !Ref AlarmTopic
      Threshold: 10
      TreatMissingData: notBreaching
      Tags:
        - Key: Product
          Value: GOV.UK
        - Key: Environment
          Value: !Ref Environment
        - Key: System
          Value: Authentication
          
  AttestationLowCompletionAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmDescription: "A large proportion of Attestation requests have not completed successfully.\nSee resolution steps in runbook: \nhttps://gov-uk.atlassian.net/wiki/spaces/GOVUK/pages/4517658627/Runbook+High+number+of+attestation+failures\n"
      AlarmName: !Sub ${AWS::StackName}-attestation-low-completion
      ComparisonOperator: LessThanOrEqualToThreshold
      DatapointsToAlarm: 1
      EvaluationPeriods: 1
      Metrics:
        - Id: lambdaLogStarted
          Label: Sum of ATTESTATION_STARTED messageCodes for lambda
          MetricStat:
            Metric:
              Dimensions:
                - Name: MessageCode
                  Value: ATTESTATION_STARTED
                - Name: Level
                  Value: INFO
              MetricName: ClientAttestationMessageCode
              Namespace: !Sub ${AWS::StackName}/LogMessages
            Period: 60
            Stat: Sum
          ReturnData: false
        - Id: lambdaLogCompleted
          Label: Sum of ATTESTATION_COMPLETED messageCodes for lambda
          MetricStat:
            Metric:
              Dimensions:
                - Name: MessageCode
                  Value: ATTESTATION_COMPLETED
                - Name: Level
                  Value: INFO
              MetricName: ClientAttestationMessageCode
              Namespace: !Sub ${AWS::StackName}/LogMessages
            Period: 60
            Stat: Sum
          ReturnData: false
        - Expression: (lambdaLogCompleted / lambdaLogStarted)*100
          Id: lambdaLogCompletePercentage
          Label: Percentage of invocations that log a SUCCESS code against a STARTED code
          ReturnData: false
        - Expression: IF(lambdaLogStarted>=50, lambdaLogCompletePercentage)
          Id: lambdaLogCompletePercentageHighTraffic
          Label: Completion threshold calculation
          ReturnData: true
      AlarmActions:
        - !Ref AlarmTopic
      OKActions:
        - !Ref AlarmTopic
      Threshold: 75
      TreatMissingData: notBreaching
      Tags:
        - Key: Product
          Value: GOV.UK
        - Key: Environment
          Value: !Ref Environment
        - Key: System
          Value: Authentication

  AttestationLow200ResponseProportionAlarm:
    Type: AWS::CloudWatch::Alarm
    DependsOn:
      - Attestation200ResponseCountMetricFilter
    Properties: 
      ActionsEnabled: !Ref EnableAlarm
      AlarmDescription: "A decrease has been detected in the proportion of 200 responses returned from the attestation endpoint, \nbased on the anomaly detection model.\nSee resolution steps in runbook: \nhttps://gov-uk.atlassian.net/wiki/spaces/GOVUK/pages/4517658627/Runbook+High+number+of+attestation+failures\n"
      AlarmName: !Sub ${AWS::StackName}-attestation-low-200-response-proportion
      ComparisonOperator: LessThanLowerThreshold
      DatapointsToAlarm: 5
      EvaluationPeriods: 5
      Metrics:
        - Id: m1
          Label: Count of 200 responses from attestation
          MetricStat:
            Metric:
              MetricName: Attestation200ResponseCount
              Namespace: !Sub ${AWS::StackName}/Responses
            Period: 120
            Stat: Sum
          ReturnData: false
        - Id: m2
          Label: Sum of API requests sent to the /oauth2/token endpoint
          MetricStat:
            Metric:
              Dimensions:
                - Name: Method
                  Value: POST
                - Name: ApiId
                  Value: !Ref ApiId
                - Name: Stage
                  Value: !Ref Environment
                - Name: Resource
                  Value: /oauth2/token
              MetricName: Count
              Namespace: AWS/ApiGateway
            Period: 120
            Stat: Sum
          ReturnData: false
        - Expression: IF(m2>=4,(m1/m2)*100)
          Id: m3
          Label: Percentage of invocations resulting in a 200 response
          ReturnData: true
        - Expression: ANOMALY_DETECTION_BAND(m3, 2)
          Id: ad1
          ReturnData: true
      AlarmActions:
        - !Ref AlarmTopic
      OKActions:
        - !Ref AlarmTopic
      ThresholdMetricId: ad1
      TreatMissingData: notBreaching
      Tags:
        - Key: Product
          Value: GOV.UK
        - Key: Environment
          Value: !Ref Environment
        - Key: System
          Value: Authentication

Outputs:
  AttestationLambdaErrorRateAlarmName:
    Value: !Ref AttestationLambdaErrorRateAlarm

  AttestationLowCompletionAlarmName:
    Value: !Ref AttestationLowCompletionAlarm

  AttestationLow200ResponseProportionAlarmName:
    Value: !Ref AttestationLow200ResponseProportionAlarm