openapi: 3.0.3
info:
  title: GOV.UK Auth Proxy
  version: 1.0.0
  description: API for exchanging OAuth2 tokens using PKCE and refresh tokens.

paths:
  /oauth2/token:
    post:
      summary: Exchange authorization code or refresh token for tokens
      x-amazon-apigateway-request-validator: Validate body
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        uri:
          Fn::Sub:
            "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${AuthProxyFunction}/invocations"
            # https://lambda.eu-west-2.amazonaws.com/2015-03-31/functions/arn:aws:lambda:eu-west-2:886436928181:function:ps-auth-auth-proxy/invocations
          # Fn::Sub: "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${AuthProxyFunction}:live/invocations"
        passthroughBehavior: "when_no_match"
      # requestBody:
      #   required: true
      #   content:
          # application/x-www-form-urlencoded:
          #   schema:
          #     oneOf:
          #       - $ref: "#/components/schemas/AuthorizationCodeGrant"
          #       - $ref: "#/components/schemas/RefreshTokenGrant"
          # application/json:
          #   schema: 
          #     $ref: ""
      parameters:
        - in: header
          name: content-type
          required: true
          schema:
            type: string
            enum:
              - application/x-www-form-urlencoded
              - application/x-www-form-urlencoded; charset=UTF-8
              - application/json
              - application/json; charset=UTF-8
        # - in: header
        #   name: x-attestation-token
        #   required: true
        #   schema:
        #     type: string
        #     # pattern: '^[\x00-\x7F]*$'
        # - in: header
        #   name: accept
        #   required: false
        #   schema:
        #     type: string
        #     maxLength: 1024
        #     # pattern: '^[\x00-\x7F]*$'
        # - in: header
        #   name: user-agent
        #   required: false
        #   schema:
        #     type: string
        #     maxLength: 1024
        #     # pattern: '^[\x00-\x7F]*$'
        # - in: header
        #   name: connection
        #   required: false
        #   schema:
        #     type: string
        #     enum:
        #       - keep-alive
        #       - close
      responses:
        "200":
          description: Tokens successfully issued
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  id_token:
                    type: string
                  refresh_token:
                    type: string
                  token_type:
                    type: string
                  expires_in:
                    type: integer
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        # "401":
        #   description: Unauthorized or invalid attestation
        #   content:
        #     application/json:
        #       schema:
        #         type: object
        #         properties:
        #           message:
        #             type: string
        # "500":
        #   description: Internal server error
        #   content:
        #     application/json:
        #       schema:
        #         type: object
        #         properties:
        #           message:
        #             type: string

components:
  schemas:
    AuthorizationCodeGrant:
      type: object
      required:
        - grant_type
        - client_id
        - redirect_uri
        - code
        - code_verifier
        - scope
      properties:
        grant_type:
          type: string
          enum:
            - authorization_code
          description: Must be "authorization_code" for this grant type
        client_id:
          type: string
          minLength: 1
          maxLength: 100
          description: The client identifier issued to the client during the registration process
        redirect_uri:
          type: string
          minLength: 1
          maxLength: 2000
        code:
          type: string
          minLength: 8
          maxLength: 512
          description: The authorization code received from the authorization server
        code_verifier:
          type: string
          minLength: 1
          maxLength: 128
          description: The PKCE code verifier used to obtain the authorization code
        scope:
          type: string
          minLength: 1
          maxLength: 1000
          description: The scope of the access request, as a space-delimited string
      additionalProperties: false

    RefreshTokenGrant:
      type: object
      required:
        - grant_type
        - refresh_token
        - client_id
      properties:
        grant_type:
          type: string
          enum:
            - refresh_token
        refresh_token:
          type: string
          minLength: 1
        client_id:
          type: string
          minLength: 1
          maxLength: 100
          description: The client identifier issued to the client during the registration process
      additionalProperties: false

  x-amazon-apigateway-request-validators:
    all: 
      - validateRequestParameters : true
      - validateRequestBody : true
  