inputs:
  role: 
    description: 'Deployment role ARN'
    required: true
  artifact_bucket:
    description: 'S3 bucket name for artifacts'
    required: true
  signing_profile:
    description: 'Signing profile name'
    required: true
runs:
  using: "composite"
  steps: 
    - name: Set up AWS creds
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.role }}
        aws-region: eu-west-2

    - name: SAM validate
      working-directory: ./auth
      run: sam validate --lint
      shell: bash  # Explicitly define the shell

    - name: SAM build and test
      run: sam build
      shell: bash  # Explicitly define the shell

    - name: Deploy SAM app
      uses: govuk-one-login/devplatform-upload-action@v3.9.4
      with:
        artifact-bucket-name: ${{ inputs.artifact_bucket }}
        signing-profile-name: ${{ inputs.signing_profile }}
        working-directory: ./auth/.aws-sam/build