name: Pre-merge checks
# Linting using cfn-lint and py-lint.
# Runs Jest unit and feature tests.
# Checks for placeholders in the sam-deploy-pipeline template.
# Checks CloudFormation templates using checkov, including GDS custom checks.

env:
  PRE_COMMIT_EXTRA_ARGS: ${{ github.ref == 'refs/heads/main' && '--from-ref HEAD^ --to-ref HEAD' || '--from-ref FETCH_HEAD --to-ref HEAD' }}

on:
 pull_request:
 merge_group:
  types: [checks_requested]
 workflow_dispatch:

jobs:
  check:
    if: github.event_name != 'pull_request' || github.event.action == 'enqueued'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      id-token: write
      contents: write
      pull-requests: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0' # Needed for git diff-tree to compare

      - name: If a stack directory and changelog is updated set the needed outputs
        run: '.github/scripts/check-changelog-requirements.sh'
        shell: bash

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Cache Python packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip3.9-${{ hashFiles('.github/workflows/pre-merge-checks.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pip3.9-

      - name: Setup Node v18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Cache Node dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: Cache Nx tasks
        uses: actions/cache@v4
        with:
          path: .nx
          key: nx-${{ hashFiles('nx.json') }}

      - name: Install Node dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts

      - run: git fetch origin main
      - name: Run pre-commit action
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: ${{ env.PRE_COMMIT_EXTRA_ARGS }}

      - name: Check for Jest test reports
        run: |
          if [ -d "test-reports" ]; then
            echo "test-reports have been generated."
            echo "test_reports=true" >> $GITHUB_ENV
          fi

      - name: Get test results history
        uses: actions/checkout@v4
        if: env.test_reports == 'true' && always()
        continue-on-error: true
        with:
          ref: test-reports-history # branch to store the GHPages
          path: test-reports-history

      - name: Jest HTML Report action
        uses: PavanMudigonda/html-reporter-github-pages@54c76f16127af1800cbc0187ac458a9e347addd4 # v1.1 - versions above that are a breaking change for this workflow
        id: test-report
        if: env.test_reports == 'true' && github.ref != 'refs/heads/main' && always()
        with:
          test_results: test-reports
          gh_pages: test-reports-history
          results_history: results-history
          keep_reports: 35

      - name: Publish Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: test-reports-history
          publish_dir: results-history
          keep_files: true
