name: Publish template versions

on:
  workflow_run:
    workflows: ["Publish templates"]
    types: [completed]
    branches: [main]

concurrency:
  group: publish-versions
  cancel-in-progress: false

permissions: {}

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0' # Needed for git diff-tree to compare

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.TEMPLATE_VERSIONS_BUCKET_ROLE }}
          aws-region: eu-west-2

      - name: Get modified stack
        shell: 'bash'
        run: |
          dir=$(git diff-tree -m --no-commit-id --name-only HEAD | sort | uniq)
          echo "Project directory $dir modified"
          echo "STACK_NAME=$dir" >> $GITHUB_ENV

      - name: Get Python version
        id: get-python-version
        shell: bash
        env:
          PYTHON_VERSION_FILE: ${{ env.STACK_NAME }}/.python-version
        run: |
          if [[ -f $PYTHON_VERSION_FILE ]]; then
            echo "python-version=$(cat "$PYTHON_VERSION_FILE")" >> "$GITHUB_OUTPUT"
          fi

      - name: Set up Python
        if: ${{ steps.get-python-version.outputs.python-version != null }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ steps.get-python-version.outputs.python-version }}
          cache-dependency-path: "**/*requirements*.txt"
          cache: pip

      - name: Publish secondary sources
        if: ${{ env.STACK_NAME == 'sam-deploy-pipeline' }}
        run: '.github/scripts/publish-secondary-sources.sh'
        shell: 'bash'
        env:
          BUCKET_NAME: ${{ secrets.TEMPLATE_VERSIONS_BUCKET_NAME }}

      - name: Publish application pipeline secondary sources
        if: ${{ env.STACK_NAME == 'application-deploy-pipeline' }}
        run: '.github/scripts/publish-application-secondary-sources.sh'
        shell: 'bash'
        env:
          BUCKET_NAME: ${{ secrets.TEMPLATE_VERSIONS_BUCKET_NAME }}

      - name: Publish authentication pipeline secondary sources
        if: ${{ env.STACK_NAME == 'auth-deploy-pipeline' }}
        run: '.github/scripts/publish-auth-secondary-sources.sh'
        shell: 'bash'
        env:
          BUCKET_NAME: ${{ secrets.TEMPLATE_VERSIONS_BUCKET_NAME }}

      - name: Publish template versions
        run: '.github/scripts/publish-versions.sh'
        env:
          STACK_NAME: ${{ env.STACK_NAME }}
          BUCKET_NAME: ${{ secrets.TEMPLATE_VERSIONS_BUCKET_NAME }}
          SIGNING_PROFILE: ${{ secrets.SIGNING_PROFILE_DEVELOPMENT }}
        shell: bash
