name: Setup test stacks
# Runs sam-deploy-pipeline tests, not including promotion tests.
# Creates the CI testing CloudFormation stacks in the morning.
# Notifies slack in case of failure.

on:
  schedule:
    # At 07:00 UTC on every Monday
    - cron: '0 7 * * MON'
  workflow_dispatch:

jobs:
  setup-test-stacks-and-run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      id-token: write
      contents: read
    concurrency: pipeline-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Set up SAM cli
        uses: aws-actions/setup-sam@v2

      - name: sam fix https://github.com/aws/aws-sam-cli/issues/4527
        run: $(dirname $(readlink $(which sam)))/pip install --force-reinstall "cryptography==38.0.4"

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.DEPLOY_TEST_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'true' # pragma: allowlist secret

      - name: Cache Python packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip3.9-${{ hashFiles('sam-deploy-pipeline/tests/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip3.9-

      - name: Provision stacks and run tests
        run: '.github/scripts/pipeline.sh'
        env:
          SIGNING_PROFILE_NAME: ${{ secrets.DEPLOY_TEST_SIGNING_PROFILE_NAME }}
          DEPLOY_TEST_BUCKET_NAME: ${{ secrets.DEPLOY_TEST_BUCKET_NAME }}
          INCLUDE_PROMOTION_TESTS: false

      - name: Send failure notification to Slack
        if: failure()
        run: |
          aws cloudwatch set-alarm-state \
          --alarm-name $SLACK_ALARM_NAME \
          --state-value ALARM \
          --state-reason "The <https://github.com/govuk-one-login/devplatform-deploy/actions|setup-test-stacks> workflow failed"
        env:
          SLACK_ALARM_NAME: ${{ secrets.SLACK_ALARM_NAME }}
