name: Teardown test stacks
# Deletes CloudFormation stacks created by Setup test stacks workflow.
# Notifies slack in case of failure.

on:
  schedule:
    # At 20:00 and 22:00 UTC on every Monday
    - cron: '0 20,22 * * MON'
  workflow_dispatch:

jobs:
  teardown-test-stacks:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.DEPLOY_TEST_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Cache Python packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip3.9-${{ hashFiles('sam-deploy-pipeline/tests/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip3.9-

      - name: Teardown stacks
        run: '.github/scripts/teardown-test-stacks.sh'
        env:
          SIGNING_PROFILE_NAME: ${{ secrets.DEPLOY_TEST_SIGNING_PROFILE_NAME }}

      - name: Send failure notification to Slack
        if: failure()
        run: |
          aws cloudwatch set-alarm-state \
          --alarm-name $SLACK_ALARM_NAME \
          --state-value ALARM \
          --state-reason "The <https://github.com/govuk-one-login/devplatform-deploy/actions|teardown-test-stacks> workflow failed"
        env:
          SLACK_ALARM_NAME: ${{ secrets.SLACK_ALARM_NAME }}
